# Generated by Django 5.0.8 on 2024-08-28 08:42

import myapp.dbo_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp',
            name='tblidx',
            field=myapp.dbo_fields.UnsignedDwordField(default=0),
        ),
    ]
