# Generated by Django 5.0.8 on 2024-08-07 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblidx', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('exp', models.IntegerField()),
                ('val', models.FloatField()),
                ('val2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
    ]
