# Generated by Django 5.0.8 on 2024-08-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item_buy_price_item_rarity_item_sell_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemTable',
        ),
    ]
