# Generated by Django 5.0.8 on 2024-08-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_item_itemtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemTable',
        ),
    ]
