# Generated by Django 5.0.8 on 2024-08-08 02:47

import myapp.dbo_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_exptable_exp_remove_exptable_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exptable',
            name='tblidx',
            field=myapp.dbo_fields.UnsignedDwordField(unique=True),
        ),
    ]
