# Generated by Django 5.0.8 on 2024-08-08 08:42

import django.db.models.deletion
import myapp.dbo_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_exptable_tblidx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblidx', myapp.dbo_fields.UnsignedDwordField(unique=True)),
                ('wszNameText', myapp.dbo_fields.UnsignedDwordField()),
                ('bySell_Type', myapp.dbo_fields.UnsignedByteField()),
                ('Tab_Name', myapp.dbo_fields.UnsignedDwordField()),
                ('dwNeedMileage', myapp.dbo_fields.UnsignedDwordField()),
            ],
        ),
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblidx', myapp.dbo_fields.UnsignedDwordField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblidx', myapp.dbo_fields.UnsignedDwordField(unique=True)),
                ('dwName', myapp.dbo_fields.UnsignedDwordField()),
                ('wszNameText', models.CharField(max_length=255)),
                ('szFile_Name', models.CharField(max_length=255)),
                ('byCoin', myapp.dbo_fields.UnsignedByteField()),
                ('bOnOff', myapp.dbo_fields.UnsignedByteField()),
                ('byType', myapp.dbo_fields.UnsignedByteField()),
                ('wfirstWinCoin', myapp.dbo_fields.UnsignedWordField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ExpTable',
            new_name='Exp',
        ),
        migrations.CreateModel(
            name='MerchantArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aItemTblidx', myapp.dbo_fields.UnsignedDwordField()),
                ('aNeedItemTblidx', myapp.dbo_fields.UnsignedDwordField()),
                ('abyNeedItemStack', myapp.dbo_fields.UnsignedByteField()),
                ('adwNeedZenny', myapp.dbo_fields.UnsignedDwordField()),
                ('id_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='SlotMachineArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aItemTblidx', myapp.dbo_fields.UnsignedDwordField()),
                ('byStack', myapp.dbo_fields.UnsignedByteField()),
                ('wQuantity', myapp.dbo_fields.UnsignedWordField()),
                ('id_slot_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.slotmachine')),
            ],
        ),
    ]
