# Generated by Django 5.0.8 on 2024-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_merchant_mob_slotmachine_rename_exptable_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotmachine',
            name='szFile_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slotmachine',
            name='wszNameText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
