# Generated by Django 5.0.8 on 2024-08-09 03:44

import myapp.dbo_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_slotmachine_szfile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotmachinearray',
            name='loop',
            field=myapp.dbo_fields.UnsignedByteField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='slotmachinearray',
            name='aItemTblidx',
            field=myapp.dbo_fields.UnsignedDwordField(default=0),
        ),
        migrations.AlterField(
            model_name='slotmachinearray',
            name='byStack',
            field=myapp.dbo_fields.UnsignedByteField(default=0),
        ),
        migrations.AlterField(
            model_name='slotmachinearray',
            name='wQuantity',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
    ]
