# Generated by Django 5.0.8 on 2024-08-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_slotmachinearray_loop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotmachinearray',
            name='loop',
        ),
    ]
