# Generated by Django 5.0.8 on 2024-08-09 12:55

import django.db.models.deletion
import myapp.dbo_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_mob_name_mob_bisdragonballdrop_mob_bshow_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantarray',
            name='id_merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MerchantArray', to='myapp.merchant'),
        ),
        migrations.AlterField(
            model_name='slotmachinearray',
            name='id_slot_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SlotMachineArray', to='myapp.slotmachine'),
        ),
        migrations.CreateModel(
            name='MobDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idxBigBag', myapp.dbo_fields.UnsignedDwordField(default=0)),
                ('byDropRate', myapp.dbo_fields.UnsignedByteField(default=0)),
                ('byTryCount', myapp.dbo_fields.UnsignedByteField(default=0)),
                ('id_mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MobDrop', to='myapp.mob')),
            ],
        ),
        migrations.CreateModel(
            name='MobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wUse_Skill_Time', myapp.dbo_fields.UnsignedWordField(default=0)),
                ('use_Skill_Tblidx', myapp.dbo_fields.UnsignedDwordField(default=0)),
                ('byUse_Skill_Basis', myapp.dbo_fields.UnsignedWordField(default=0)),
                ('wUse_Skill_LP', myapp.dbo_fields.UnsignedByteField(default=0)),
                ('id_mob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MobSkill', to='myapp.mob')),
            ],
        ),
    ]
