# Generated by Django 4.2.15 on 2024-08-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_merchantarray_id_merchant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='wPerfectWinSolo',
            new_name='wPerfectWin',
        ),
        migrations.RenameField(
            model_name='exp',
            old_name='wPerfectWinTeam',
            new_name='wStageDraw',
        ),
        migrations.RenameField(
            model_name='exp',
            old_name='wStageDrawSolo',
            new_name='wStageLose',
        ),
        migrations.RenameField(
            model_name='exp',
            old_name='wStageDrawTeam',
            new_name='wStageWin',
        ),
        migrations.RenameField(
            model_name='exp',
            old_name='wStageLoseSolo',
            new_name='wWin',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='wStageLoseTeam',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='wStageWinSolo',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='wStageWinTeam',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='wWinSolo',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='wWinTeam',
        ),
    ]
