# Generated by Django 4.2.15 on 2024-08-11 10:00

from django.db import migrations
import myapp.dbo_fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_wperfectwinsolo_exp_wperfectwin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp',
            name='wPerfectWin',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='wStageDraw',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='wStageLose',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='wStageWin',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='wWin',
        ),
        migrations.AddField(
            model_name='exp',
            name='wPerfectWinSolo',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AddField(
            model_name='exp',
            name='wPerfectWinTeam',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AddField(
            model_name='exp',
            name='wStageDrawSolo',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AddField(
            model_name='exp',
            name='wStageDrawTeam',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AddField(
            model_name='exp',
            name='wStageLoseSolo',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AddField(
            model_name='exp',
            name='wStageLoseTeam',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AddField(
            model_name='exp',
            name='wStageWinSolo',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AddField(
            model_name='exp',
            name='wStageWinTeam',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AddField(
            model_name='exp',
            name='wWinSolo',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AddField(
            model_name='exp',
            name='wWinTeam',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AlterField(
            model_name='exp',
            name='dwEngDefenceRef',
            field=myapp.dbo_fields.UnsignedDwordField(default=0),
        ),
        migrations.AlterField(
            model_name='exp',
            name='dwExp',
            field=myapp.dbo_fields.UnsignedDwordField(default=0),
        ),
        migrations.AlterField(
            model_name='exp',
            name='dwMobExp',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AlterField(
            model_name='exp',
            name='dwMobZenny',
            field=myapp.dbo_fields.UnsignedDwordField(default=0),
        ),
        migrations.AlterField(
            model_name='exp',
            name='dwNeed_Exp',
            field=myapp.dbo_fields.UnsignedDwordField(default=0),
        ),
        migrations.AlterField(
            model_name='exp',
            name='dwPhyDefenceRef',
            field=myapp.dbo_fields.UnsignedDwordField(default=0),
        ),
        migrations.AlterField(
            model_name='exp',
            name='wNormal_Race',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
        migrations.AlterField(
            model_name='exp',
            name='wSuperRace',
            field=myapp.dbo_fields.UnsignedWordField(default=0),
        ),
    ]
